services:
  - type: web
    name: haircut-backend
    env: docker
    repo: https://github.com/amiradmin/haircut-scheduler.git
    branch: master  # Make sure this is your default GitHub branch
    dockerfilePath: Dockerfile
    envVars:
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: DATABASE_NAME
        value: "haircut_db"
      - key: DATABASE_USER
        value: "haircut_user"
      - key: DATABASE_PASSWORD
        value: "securepassword123"
      - key: DATABASE_HOST
        value: haircut-db.onrender.com  # Replace with actual DB hostname
      - key: DATABASE_PORT
        value: "5432"
